---
- hosts: localhost
  gather_facts: false
  tasks: 
    - command: "ls /root/tomcat7"
      register: tomcat7_out
    - debug: var=tomcat7_out

    - command: "ls /root/tomcat8"
      register: tomcat8_out
    - debug: var=tomcat8_out

    - command: "ls /root/tomcat9"
      register: tomcat9_out
    - debug: var=tomcat9_out

        
