---
- name: Sample
  hosts: db
  tasks: 
    - name: Installing package
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - docker
        - wget
        - tree
