---
- name: Install nmap
  hosts: web
  tasks:
    - name: Install nmap
      yum:
        name: nmap
        state: present
      loop: "{{ ansible_mounts }}"
      when: item.mount == "/" and item.size_available > 500000 
